### ISSUE TITLE
pyproject.toml: remove extra files from build targets

### ISSUE THREAD

**Issue by showa-yojyo** [showa-yojyo/dqutils#38]
開発環境でしか必要でないファイルは wheel からだいたい除外する。一方 `sdist` はコードを全部含める。

```toml
[tool.hatch.build]
exclude = [
    "/.*",
    "Pipfile*",
]
[tool.hatch.build.targets.wheel]
exclude = [
    "/tests",
]
ignore-vcs = true
```
